apiVersion: v1
kind: Service
metadata:
  labels:
    service: my-service
  name: my-service
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    service: my-service
